### ISSUE TITLE
Mission XP

### ISSUE THREAD

**Issue by OldManwithaCat** [NBKRedSpy/BtShowXp#4]
Unable to see if pilots will get full xp for missions now. How much xp the pilot has, and corrupted xp still work fine. Just doesn't show anything else currently.
I have tried changing the mod.json files but still doesn't work.

**Comment by NBKRedSpy** [comment]
Is the game running BEX, vanilla, or some other mod pack?
Are there other mods included?

**Comment by OldManwithaLawn** [comment]
I'm running BEX with CAC-C, Bigger Drops and the TBD mod.
I've also included Don't Shoot the Dead, Melee Mover, Stop Over Paying Pilots and Commander Background and Quirks.

**Comment by NBKRedSpy** [comment]
I created a BEX specific version which should fix the CAC-C compatibility.

It looks like a there was a change in CAC-C a while back that is conflicting.

https://github.com/NBKRedSpy/BtShowXp/releases/tag/1.3.2.0%2BBEX

**Comment by OldManwithaCat** [comment]
Very nice. Just downloaded and tested it. Working perfectly. Thank you so much :)
